// <auto-generated />
using System;
using EvaWoods.Infrastructure.Persistence;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Npgsql.EntityFrameworkCore.PostgreSQL.Metadata;

#nullable disable

namespace EvaWoods.Infrastructure.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260731094127_AdaugaCalculMateriale")]
    partial class AdaugaCalculMateriale
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "9.0.18")
                .HasAnnotation("Relational:MaxIdentifierLength", 63);

            NpgsqlModelBuilderExtensions.UseIdentityByDefaultColumns(modelBuilder);

            modelBuilder.Entity("EvaWoods.Domain.Cheltuieli.Cheltuiala", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<DateTime>("Data")
                        .HasColumnType("date");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descriere")
                        .IsRequired()
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<Guid?>("FurnizorId")
                        .HasColumnType("uuid");

                    b.Property<bool>("IncludeInBuget")
                        .HasColumnType("boolean");

                    b.Property<string>("MetodaPlata")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("NumarFactura")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<string>("Observatii")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal>("ProcentTva")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ProiectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusPlata")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subcategorie")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<decimal>("Total")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("Tva")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ValoareFaraTva")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("FurnizorId");

                    b.HasIndex("ProiectId");

                    b.ToTable("Cheltuieli", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Cheltuieli.Furnizor", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.HasKey("Id");

                    b.ToTable("Furnizori", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Clienti.Client", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataUltimeiActivitati")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Email")
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Judet")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Localitate")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Telefon")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Nume");

                    b.ToTable("Clienti", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Materiale.CalculMaterial", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCalcul")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Erori")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<int>("FoiEstimate")
                        .HasColumnType("integer");

                    b.Property<decimal>("FoiTeoretice")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("LayoutJson")
                        .HasColumnType("text");

                    b.Property<Guid>("MaterialProdusId")
                        .HasColumnType("uuid");

                    b.Property<int>("NumarBucati")
                        .HasColumnType("integer");

                    b.Property<int>("NumarTipuriPiese")
                        .HasColumnType("integer");

                    b.Property<decimal>("PierdereProcent")
                        .HasColumnType("numeric(5,2)");

                    b.Property<Guid>("ProiectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("SuprafataPieseM2")
                        .HasColumnType("numeric(12,4)");

                    b.Property<decimal>("UtilizareProcent")
                        .HasColumnType("numeric(5,2)");

                    b.HasKey("Id");

                    b.HasIndex("MaterialProdusId");

                    b.HasIndex("ProiectId", "MaterialProdusId")
                        .IsUnique();

                    b.ToTable("CalculeMateriale", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Piese.CorpProiect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<Guid>("ProiectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.ToTable("CorpuriProiect", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Piese.Piesa", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("CantLaturiLungi")
                        .HasColumnType("integer");

                    b.Property<int>("CantLaturiScurte")
                        .HasColumnType("integer");

                    b.Property<int>("Cantitate")
                        .HasColumnType("integer");

                    b.Property<Guid?>("CorpId")
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("DirectieFibra")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<decimal?>("GrosimeMm")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal>("LatimeMm")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal>("LungimeMm")
                        .HasColumnType("numeric(10,2)");

                    b.Property<Guid?>("MaterialCantProdusId")
                        .HasColumnType("uuid");

                    b.Property<Guid?>("MaterialProdusId")
                        .HasColumnType("uuid");

                    b.Property<string>("Nume")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Observatii")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<bool>("PermiteRotire")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProiectId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("CorpId");

                    b.HasIndex("MaterialCantProdusId");

                    b.HasIndex("MaterialProdusId");

                    b.HasIndex("ProiectId");

                    b.ToTable("Piese", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Produse.Produs", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Categorie")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("Cod")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime>("DataUltimeiActualizariPret")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsteActiv")
                        .HasColumnType("boolean");

                    b.Property<Guid?>("FurnizorId")
                        .HasColumnType("uuid");

                    b.Property<decimal?>("GrosimeMm")
                        .HasColumnType("numeric(6,2)");

                    b.Property<decimal?>("KerfMm")
                        .HasColumnType("numeric(5,2)");

                    b.Property<decimal?>("LatimeFoaieMm")
                        .HasColumnType("numeric(10,2)");

                    b.Property<decimal?>("LungimeFoaieMm")
                        .HasColumnType("numeric(10,2)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("Observatii")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<bool>("PermiteRotire")
                        .HasColumnType("boolean");

                    b.Property<decimal>("PretAchizitie")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal?>("PretCalcul")
                        .HasColumnType("numeric(12,2)");

                    b.Property<decimal>("ProcentTva")
                        .HasColumnType("numeric(5,2)");

                    b.Property<string>("Subcategorie")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("UM")
                        .IsRequired()
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.HasKey("Id");

                    b.HasIndex("Cod")
                        .IsUnique();

                    b.HasIndex("FurnizorId");

                    b.ToTable("Produse", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.IstoricStatusProiect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataSchimbare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Observatie")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<Guid>("ProiectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StatusNou")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("StatusVechi")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Utilizator")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.ToTable("IstoricStatusProiect", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.NotaInternaProiect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("Autor")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<DateTime?>("DataModificare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<bool>("EsteFixata")
                        .HasColumnType("boolean");

                    b.Property<bool>("EsteRezolvata")
                        .HasColumnType("boolean");

                    b.Property<Guid>("ProiectId")
                        .HasColumnType("uuid");

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.ToTable("NoteInterneProiect", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.Proiect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("AccesAuto")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("AdresaMontaj")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<bool?>("AreLift")
                        .HasColumnType("boolean");

                    b.Property<decimal?>("BugetAlocat")
                        .HasColumnType("numeric(12,2)");

                    b.Property<Guid>("ClientId")
                        .HasColumnType("uuid");

                    b.Property<string>("CodProiect")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("Descriere")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("DescriereUrmatorulPas")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("Etaj")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<string>("IntervalOrarPreferat")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.Property<string>("LocParcare")
                        .HasMaxLength(300)
                        .HasColumnType("character varying(300)");

                    b.Property<string>("Note")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("character varying(200)");

                    b.Property<string>("ObservatiiClient")
                        .HasMaxLength(2000)
                        .HasColumnType("character varying(2000)");

                    b.Property<string>("ObservatiiTransport")
                        .HasMaxLength(1000)
                        .HasColumnType("character varying(1000)");

                    b.Property<string>("PersoanaContactMontaj")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<int>("Progres")
                        .HasColumnType("integer");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(20)
                        .HasColumnType("character varying(20)");

                    b.Property<string>("Subtip")
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)")
                        .HasColumnName("TipMobilier");

                    b.Property<DateTime?>("TermenLimita")
                        .HasColumnType("date");

                    b.Property<DateTime?>("TermenUrmatorulPas")
                        .HasColumnType("date");

                    b.Property<string>("TipPrincipal")
                        .HasMaxLength(30)
                        .HasColumnType("character varying(30)");

                    b.Property<decimal>("Valoare")
                        .HasColumnType("numeric(12,2)");

                    b.HasKey("Id");

                    b.HasIndex("ClientId");

                    b.HasIndex("CodProiect")
                        .IsUnique();

                    b.ToTable("Proiecte", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.SpatiuProiect", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<DateTime>("DataCreare")
                        .HasColumnType("timestamp with time zone");

                    b.Property<int?>("InaltimeMm")
                        .HasColumnType("integer");

                    b.Property<string>("Nume")
                        .IsRequired()
                        .HasMaxLength(150)
                        .HasColumnType("character varying(150)");

                    b.Property<string>("Orientare")
                        .HasMaxLength(50)
                        .HasColumnType("character varying(50)");

                    b.Property<Guid>("ProiectId")
                        .HasColumnType("uuid");

                    b.Property<string>("StarePardoseala")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<string>("StarePereti")
                        .HasMaxLength(500)
                        .HasColumnType("character varying(500)");

                    b.Property<decimal?>("Suprafata")
                        .HasColumnType("numeric(8,2)");

                    b.Property<string>("TipSpatiu")
                        .HasMaxLength(100)
                        .HasColumnType("character varying(100)");

                    b.HasKey("Id");

                    b.HasIndex("ProiectId");

                    b.ToTable("SpatiiProiect", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Infrastructure.Identity.ApplicationUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("integer");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("FullName")
                        .IsRequired()
                        .HasColumnType("text");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("boolean");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("timestamp with time zone");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("text");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("text");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("boolean");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("text");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("boolean");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.ToTable("AspNetUsers", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("uuid");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("character varying(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex");

                    b.ToTable("AspNetRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetRoleClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("integer");

                    NpgsqlPropertyBuilderExtensions.UseIdentityByDefaultColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("text");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("text");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("text");

                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AspNetUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<Guid>("RoleId")
                        .HasColumnType("uuid");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("AspNetUserRoles", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("uuid");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("text");

                    b.Property<string>("Name")
                        .HasColumnType("text");

                    b.Property<string>("Value")
                        .HasColumnType("text");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AspNetUserTokens", (string)null);
                });

            modelBuilder.Entity("EvaWoods.Domain.Cheltuieli.Cheltuiala", b =>
                {
                    b.HasOne("EvaWoods.Domain.Cheltuieli.Furnizor", null)
                        .WithMany()
                        .HasForeignKey("FurnizorId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EvaWoods.Domain.Proiecte.Proiect", null)
                        .WithMany()
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaWoods.Domain.Materiale.CalculMaterial", b =>
                {
                    b.HasOne("EvaWoods.Domain.Produse.Produs", null)
                        .WithMany()
                        .HasForeignKey("MaterialProdusId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaWoods.Domain.Proiecte.Proiect", null)
                        .WithMany()
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaWoods.Domain.Piese.CorpProiect", b =>
                {
                    b.HasOne("EvaWoods.Domain.Proiecte.Proiect", null)
                        .WithMany()
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaWoods.Domain.Piese.Piesa", b =>
                {
                    b.HasOne("EvaWoods.Domain.Piese.CorpProiect", null)
                        .WithMany()
                        .HasForeignKey("CorpId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EvaWoods.Domain.Produse.Produs", null)
                        .WithMany()
                        .HasForeignKey("MaterialCantProdusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EvaWoods.Domain.Produse.Produs", null)
                        .WithMany()
                        .HasForeignKey("MaterialProdusId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("EvaWoods.Domain.Proiecte.Proiect", null)
                        .WithMany()
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaWoods.Domain.Produse.Produs", b =>
                {
                    b.HasOne("EvaWoods.Domain.Cheltuieli.Furnizor", null)
                        .WithMany()
                        .HasForeignKey("FurnizorId")
                        .OnDelete(DeleteBehavior.SetNull);
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.IstoricStatusProiect", b =>
                {
                    b.HasOne("EvaWoods.Domain.Proiecte.Proiect", null)
                        .WithMany()
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.NotaInternaProiect", b =>
                {
                    b.HasOne("EvaWoods.Domain.Proiecte.Proiect", null)
                        .WithMany()
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.Proiect", b =>
                {
                    b.HasOne("EvaWoods.Domain.Clienti.Client", null)
                        .WithMany()
                        .HasForeignKey("ClientId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("EvaWoods.Domain.Proiecte.SpatiuProiect", b =>
                {
                    b.HasOne("EvaWoods.Domain.Proiecte.Proiect", null)
                        .WithMany()
                        .HasForeignKey("ProiectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("EvaWoods.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("EvaWoods.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<System.Guid>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole<System.Guid>", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("EvaWoods.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("EvaWoods.Infrastructure.Identity.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
